name: Deploy
on:
    push:
        branches:
            - staging
            - master
    workflow_dispatch:
env:
    TEST_NAME: test
    TEST_NAME_ID: ${TEST_NAME}/${GITHUB_RUN_ID}
    TEST_NAME_OTHER: ${TEST_NAME}/other
    TEST_NAME_OTHER_2: ${TEST_NAME_OTHER}/2
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3

            -   name: Print
                run: |
                    echo ${{env.TEST_NAME}}
                    echo ${{env.TEST_NAME_ID}}
                    echo ${{env.TEST_NAME_OTHER}}
                    echo ${{env.TEST_NAME_OTHER_2}}
                    echo ${GITHUB_RUN_ID}
                    echo ${GITHUB_RUN_NUMBER}
                    ((previous = ${GITHUB_RUN_NUMBER} - 1))
                    echo $previous
                    echo ${{github.event.pull_request.labels}}
                    git show ${GITHUB_SHA} --no-patch --pretty=format:%s
                    LAST_COMMIT_MESSAGE=`git show ${GITHUB_SHA} --no-patch --pretty=format:%s`
                    echo "---"
                    echo ${LAST_COMMIT_MESSAGE}
                    RELEASE_TYPE=`echo $LAST_COMMIT_MESSAGE | grep -Eq "^Merge pull request #[0-9]+ from martinvy/(master|staging)$" && echo "feature" || echo "bugfix"`
                    echo ${RELEASE_TYPE}
                    echo "${{github.event.head_commit.message}}"
                    
                    RELEASE_TYPE_2 = `echo "${{github.event.head_commit.message}}" | grep -Eq "^Merge pull request #[0-9]+ from martinvy/staging" && echo "feature" || echo "bugfix"``
                    echo ${RELEASE_TYPE_2}
