name: Deploy
on:
    push:
        branches:
            - staging
            - master
    workflow_dispatch:
env:
    TEST_NAME: test/${GITHUB_RUN_ID}
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                with:
                    ref: master

            -   name: Print
                run: |
                    echo ${{env.TEST_NAME}}
                    echo ${GITHUB_RUN_ID}
                    echo ${GITHUB_RUN_NUMBER}
                    echo `${GITHUB_RUN_NUMBER } - 1`
                    echo ${{github.event.pull_request.labels}}
