name: Dev -> Staging
on:
  push:
    branches:
      - dev
jobs:
  dev-to-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: staging
      - name: Reset promotion branch
        run: |
          git fetch origin dev:dev
          git checkout dev
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
