name: Merge down
on:
    push:
        branches:
            - master
            - staging
jobs:
    merge-down:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master

            -   name: Merge Master -> Staging
                uses: everlytic/branch-merge@1.1.2
                with:
                    source_ref: master
                    target_branch: staging
                    commit_message_template: Merge branch master to staging
                    github_token: ${{ github.token }}

            -   name: Merge Staging -> Dev
                uses: everlytic/branch-merge@1.1.2
                with:
                    source_ref: staging
                    target_branch: dev
                    commit_message_template: Merge branch staging to dev
                    github_token: ${{ github.token }}
