name: Staging -> Master
on:
    push:
        branches:
            - staging
jobs:
    staging-to-master:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
                with:
                    ref: master
            -   name: Reset promotion branch
                run: |
                    git fetch origin staging:staging
                    git reset --hard staging
            -   name: Create Pull Request
                uses: peter-evans/create-pull-request@v3
                with:
                    branch: staging
                    title: Staging -> Master
